In [2]:
import numpy as np

In [3]:
my_list = [10,20,30,40]

In [4]:
type(my_list)

list

In [5]:
# diziler daha sıkı kuralları olur
np.array(my_list)

array([10, 20, 30, 40])

In [ ]:
# np.array bana matematiksel işlemler için kolaylık sağlar
my_numpy_array = np.array(my_list)

In [7]:
type(my_numpy_array)

numpy.ndarray

In [8]:
my_numpy_array.max()

40

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.random.random(5)

array([0.7811201 , 0.7187305 , 0.22738387, 0.89447764, 0.66156825])

In [16]:
# array arithmetic

In [15]:
my_list1 = [1,2]

In [20]:
my_list2 = [3,4]

In [21]:
my_list1 + my_list2

[1, 2, 3, 4]

In [22]:
my_numpy_arr1 = np.array(my_list1)

In [23]:
my_numpy_arr2 = np.array(my_list2)

In [24]:
my_numpy_arr1 + my_numpy_arr2

array([4, 6])

In [26]:
my_numpy_arr1 * my_numpy_arr2

array([3, 8])

In [27]:
my_numpy_arr1 * 5

array([ 5, 10])

In [28]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [29]:
other_arr = np.array([10,20,30,40])

In [30]:
other_arr.min()

10

In [31]:
other_arr.sum()

100

In [32]:
# dizi boyutları aynı olmalı yoksa hata verir

Broadcasting, farklı boyutlardaki (shape’leri farklı) dizilerin (array) aritmetik işlemler sırasında otomatik olarak aynı boyuta genişletilmesi işlemidir.Normalde iki dizinin toplama, çıkarma gibi işlemlerde kullanılabilmesi için boyutlarının (shape) aynı olması gerekir.
Ancak broadcasting sayesinde — belli kurallara uyuyorsa — küçük dizi otomatik olarak büyük dizinin boyutuna “yayılır” (broadcast edilir).

In [ ]:
# arange & indexing

In [33]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [35]:
np_arr = np.arange(0,10)

In [36]:
np_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np_arr[1:4:]

array([1, 2, 3])

In [38]:
np_arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
# random

In [40]:
np.random.randn(4)

array([ 0.56018619,  0.70780532,  0.20140943, -0.43035709])

In [41]:
np.random.randn(4,4)

array([[ 0.7107128 , -0.67179605,  1.94255042,  0.50164272],
       [-0.32678963, -1.29659844, -0.64177471,  0.68971798],
       [ 3.27763784,  0.723905  , -1.41374343, -1.84469314],
       [ 0.35348324,  1.39841944,  0.37998022,  1.09053487]])

In [ ]:
np.random.randint(1,300,5) # 5 tam sayı verir

array([251,  79,  56,  74, 168])