In [1]:
import numpy as np

In [2]:
my_mtrix = [[5,10],[15,20]]

In [3]:
my_mtrix[0]

[5, 10]

In [4]:
my_mtrix[0][1]

10

In [ ]:
# row * column

In [5]:
numpy_matrix = np.array([[5,10],[15,20]])

In [6]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [7]:
numpy_matrix[1][0]

15

In [8]:
numpy_matrix.sum()

50

In [10]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.random.random((3,2))

array([[0.28069302, 0.18827216],
       [0.04976652, 0.27333035],
       [0.71051828, 0.77468254]])

In [13]:
# matrix arithmetic

In [15]:
first_array = np.array([[10,20],[30,40]])

In [16]:
second_array = np.array([[5,15],[25,35]])

In [17]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [18]:
first_array

array([[10, 20],
       [30, 40]])

In [ ]:
third_array = np.array([[50,60]]) # broadcasting yapar

In [20]:
third_array

array([[50, 60]])

In [21]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [22]:
fourth_array = np.array([[10,20,30,40,50,60]])

In [23]:
fourth_array

array([[10, 20, 30, 40, 50, 60]])

In [ ]:
first_array + fourth_array # HATA

ValueError: operands could not be broadcast together with shapes (2,2) (1,6) 

In [25]:
first_array * 2

array([[20, 40],
       [60, 80]])

In [26]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [27]:
third_array = np.array([[10],[20]])

In [28]:
third_array

array([[10],
       [20]])

In [30]:
third_array.shape

(2, 1)

In [31]:
first_array.shape

(2, 2)

In [32]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [33]:
# matrix multiplication

In [34]:
first_array

array([[10, 20],
       [30, 40]])

In [35]:
second_array

array([[ 5, 15],
       [25, 35]])

In [36]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [ ]:
# dot product
# 1*3 3*2 

In [37]:
first_matrix = np.array([[10,20,30]])

In [38]:
first_matrix

array([[10, 20, 30]])

In [39]:
first_matrix.shape

(1, 3)

In [40]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [41]:
second_matrix.shape

(3, 2)

In [ ]:
# first_matrix * second_matrix

In [42]:
sonuc = first_matrix.dot(second_matrix)

In [43]:
sonuc

array([[120, 180]])