In [2]:
import numpy as np

In [3]:
new_array = np.random.randint(1,100,20)

In [ ]:
new_array

array([61, 28, 71, 88, 94, 67, 71, 65, 45, 84, 97, 17, 74, 53, 32, 79, 90,
       29, 57, 17])

In [5]:
new_array > 25

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False])

In [6]:
new_array[new_array > 25]

array([61, 28, 71, 88, 94, 67, 71, 65, 45, 84, 97, 74, 53, 32, 79, 90, 29,
       57])

In [7]:
new_array[new_array < 25]

array([17, 17])

In [ ]:
# transpose & reshape

In [8]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [9]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [10]:
matrix_array.shape

(3, 2)

In [ ]:
matrix_array.transpose() # sütun ve satırları değiştirir

array([[10, 20, 30],
       [20, 30, 40]])

In [12]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
random_array = np.random.random((6,1))

In [14]:
random_array

array([[0.18829493],
       [0.78907254],
       [0.57176233],
       [0.20431166],
       [0.41951271],
       [0.44975051]])

In [15]:
random_array.shape

(6, 1)

In [ ]:
random_array.reshape(2,3) #sıralamayı bozmadan şeklini değiştirir

array([[0.18829493, 0.78907254, 0.57176233],
       [0.20431166, 0.41951271, 0.44975051]])

In [ ]:
# z-score

In [17]:
data = np.array([10,12,13,15,18,25,100,105])

In [19]:
# outlier

In [20]:
mean = np.mean(data)

In [21]:
mean

37.25

In [22]:
data.sum() / len(data)

37.25

In [23]:
std = np.std(data)

In [25]:
std

37.9333296719389

In [26]:
z_scores = (data - mean) / std

In [27]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [28]:
z_scores[z_scores > 1]

array([1.65421809, 1.78602829])

In [29]:
data[z_scores > 1]

array([100, 105])

In [ ]:
# math equations

In [ ]:
# 2x + 3y = 8 and 5x + 7y = 19

In [ ]:
#coefficient

In [30]:
A = np.array([[2,3],[5,7]])

In [ ]:
#constant

In [31]:
b = np.array([8,19])

In [32]:
solution = np.linalg.solve(A,b)

In [33]:
solution

array([1., 2.])